window.MELI_SERVICE_CATEGORIES = [
  { id: 'all', icon: 'ALL', name: 'Všechny služby', desc: 'Kompletní nabídka' },
  { id: 'massage', icon: 'M', name: 'Masáže', desc: 'Relaxace a regenerace' },
  { id: 'cosmetics', icon: 'K', name: 'Kosmetika', desc: 'Péče o pleť' },
  { id: 'depilation', icon: 'D', name: 'Depilace', desc: 'Obličej a tělo' },
  { id: 'manicure', icon: 'N', name: 'Manikúra', desc: 'Ruce a gel lak' },
  { id: 'pedicure', icon: 'P', name: 'Pedikúra', desc: 'Chodidla a nehty' },
  { id: 'nailart', icon: 'Z', name: 'Zdobení nehtů', desc: 'Design a efekty' },
  { id: 'modelage', icon: 'G', name: 'Modeláž nehtů', desc: 'Gelové a akrylové' },
  { id: 'browslashes', icon: 'O', name: 'Obočí & řasy', desc: 'Lifting, barvení, řasy' },
  { id: 'voucher', icon: 'V', name: 'Poukazy', desc: 'Dárkové poukazy' }
];

window.MELI_SERVICES = [
  { id: 'massage-body-60', category: 'massage', name: 'Masáž těla 60 min', desc: 'Tradiční vietnamská nebo relaxační masáž těla.', price: 850, priceText: '850 Kč', duration: 60, tags: ['masáž', 'tělo'] },
  { id: 'massage-body-90', category: 'massage', name: 'Masáž těla 90 min', desc: 'Delší masáž pro hlubší uvolnění a regeneraci.', price: 1200, priceText: '1 200 Kč', duration: 90, tags: ['masáž', 'tělo'] },
  { id: 'massage-special-90', category: 'massage', name: 'Meli Special masáž 90 min', desc: 'Speciální kombinovaná masáž pro maximální odpočinek.', price: 1450, priceText: '1 450 Kč', duration: 90, tags: ['special', 'relax'] },
  { id: 'massage-combo-30', category: 'massage', name: 'Kombo záda, šíje, hlava & obličej 30 min', desc: 'Rychlé uvolnění nejvíce namáhaných partií.', price: 650, priceText: '650 Kč', duration: 30, tags: ['záda', 'šíje', 'hlava'] },
  { id: 'massage-combo-60', category: 'massage', name: 'Kombo záda, šíje, hlava & obličej 60 min', desc: 'Delší kombinovaná procedura pro relaxaci i úlevu.', price: 980, priceText: '980 Kč', duration: 60, tags: ['záda', 'šíje', 'obličej'] },
  { id: 'massage-head-face-30', category: 'massage', name: 'Masáž hlavy & obličeje 30 min', desc: 'Jemná masáž pro odpočinek, pleť a uvolnění napětí.', price: 450, priceText: '450 Kč', duration: 30, tags: ['hlava', 'obličej'] },
  { id: 'massage-back-neck-30', category: 'massage', name: 'Masáž zad & šíje 30 min', desc: 'Cílená péče na záda, krk a šíji.', price: 650, priceText: '650 Kč', duration: 30, tags: ['záda', 'šíje'] },
  { id: 'massage-back-neck-60', category: 'massage', name: 'Masáž zad & šíje 60 min', desc: 'Delší uvolnění zad a šíje po náročném dni.', price: 980, priceText: '980 Kč', duration: 60, tags: ['záda', 'šíje'] },
  { id: 'massage-feet-30', category: 'massage', name: 'Masáž nohou 30 min', desc: 'Relaxační masáž unavených chodidel a lýtek.', price: 550, priceText: '550 Kč', duration: 30, tags: ['nohy'] },
  { id: 'massage-feet-60', category: 'massage', name: 'Masáž nohou 60 min', desc: 'Kompletní péče pro unavené nohy.', price: 850, priceText: '850 Kč', duration: 60, tags: ['nohy'] },
  { id: 'massage-couple-60', category: 'massage', name: 'Párová masáž 60 min', desc: 'Společná relaxace ve dvou podle výběru typu masáže.', price: 1700, priceText: 'od 1 700 Kč', duration: 60, tags: ['párová', 'relax'] },
  { id: 'massage-couple-90', category: 'massage', name: 'Párová masáž 90 min', desc: 'Delší párový rituál pro dva.', price: 2400, priceText: 'od 2 400 Kč', duration: 90, tags: ['párová', 'relax'] },

  { id: 'cos-basic', category: 'cosmetics', name: 'Základní kosmetické ošetření 45 min', desc: 'Očištění pleti, peeling, masáž obličeje, maska, sérum a krém.', price: 550, priceText: '550 Kč', duration: 45, tags: ['pleť', 'maska'] },
  { id: 'cos-special', category: 'cosmetics', name: 'Speciální kosmetické ošetření 60 min', desc: 'Hloubková péče včetně ultrazvukové špachtle, masky a séra.', price: 850, priceText: '850 Kč', duration: 60, tags: ['pleť', 'ultrazvuk'] },
  { id: 'cos-detox', category: 'cosmetics', name: 'Detoxikační ošetření 60 min', desc: 'Detox péče s maskou, masáží, acid sérem a zklidňujícím krémem.', price: 900, priceText: '900 Kč', duration: 60, tags: ['detox', 'pleť'] },

  { id: 'dep-face', category: 'depilation', name: 'Depilace obličeje 45 min', desc: 'Komplexní depilace obličejových partií.', price: 600, priceText: '600 Kč', duration: 45, tags: ['obličej'] },
  { id: 'dep-brow', category: 'depilation', name: 'Depilace / úprava obočí 15 min', desc: 'Rychlá úprava obočí depilací.', price: 180, priceText: '180 Kč', duration: 15, tags: ['obočí'] },
  { id: 'dep-lip', category: 'depilation', name: 'Depilace horního rtu 15 min', desc: 'Jemná depilace horního rtu.', price: 170, priceText: '170 Kč', duration: 15, tags: ['horní ret'] },
  { id: 'dep-chin', category: 'depilation', name: 'Depilace brady 15 min', desc: 'Depilace oblasti brady.', price: 180, priceText: '180 Kč', duration: 15, tags: ['brada'] },
  { id: 'dep-cheeks', category: 'depilation', name: 'Depilace tváří 15 min', desc: 'Jemná depilace tváří.', price: 230, priceText: '230 Kč', duration: 15, tags: ['tváře'] },
  { id: 'dep-armpit', category: 'depilation', name: 'Depilace podpaží 15 min', desc: 'Rychlá depilace podpaží.', price: 400, priceText: '400 Kč', duration: 15, tags: ['podpaží'] },
  { id: 'dep-arms-hands', category: 'depilation', name: 'Depilace paže a ruce 25 min', desc: 'Depilace paží a rukou.', price: 410, priceText: '410 Kč', duration: 25, tags: ['paže', 'ruce'] },
  { id: 'dep-belly', category: 'depilation', name: 'Depilace břicha 30 min', desc: 'Depilace oblasti břicha.', price: 400, priceText: '400 Kč', duration: 30, tags: ['břicho'] },
  { id: 'dep-back', category: 'depilation', name: 'Depilace zad 60-90 min', desc: 'Depilace zad podle rozsahu.', price: 680, priceText: '680 Kč', duration: 75, tags: ['záda'] },
  { id: 'dep-thighs', category: 'depilation', name: 'Depilace stehen 30 min', desc: 'Depilace stehen.', price: 450, priceText: '450 Kč', duration: 30, tags: ['stehna'] },
  { id: 'dep-calves', category: 'depilation', name: 'Depilace lýtek 30 min', desc: 'Depilace lýtek.', price: 450, priceText: '450 Kč', duration: 30, tags: ['lýtka'] },
  { id: 'dep-buttocks', category: 'depilation', name: 'Depilace hýždí 30 min', desc: 'Depilace oblasti hýždí.', price: 450, priceText: '450 Kč', duration: 30, tags: ['hýždě'] },
  { id: 'dep-bikini', category: 'depilation', name: 'Depilace třísel 15 min', desc: 'Depilace třísel.', price: 400, priceText: '400 Kč', duration: 15, tags: ['třísla'] },

  { id: 'mani-woman', category: 'manicure', name: 'Manikúra klasik dámská', desc: 'Klasická úprava nehtů a kůžičky.', price: 200, priceText: '200 Kč', duration: 30, tags: ['klasik'] },
  { id: 'mani-man', category: 'manicure', name: 'Manikúra klasik pánská', desc: 'Klasická pánská manikúra.', price: 200, priceText: '200 Kč', duration: 30, tags: ['pánská'] },
  { id: 'mani-gel-lak', category: 'manicure', name: 'Manikúra & Gel lak', desc: 'Manikúra s aplikací gel laku.', price: 380, priceText: '380 Kč', duration: 60, tags: ['gel lak'] },
  { id: 'mani-removal', category: 'manicure', name: 'Odstranění nehtů', desc: 'Šetrné odstranění staré modeláže nebo gel laku.', price: 200, priceText: '200 Kč', duration: 30, tags: ['odstranění'] },

  { id: 'pedi-woman', category: 'pedicure', name: 'Pedikúra klasik dámská', desc: 'Klasická dámská pedikúra.', price: 420, priceText: '420 Kč', duration: 60, tags: ['klasik'] },
  { id: 'pedi-man', category: 'pedicure', name: 'Pedikúra klasik pánská', desc: 'Klasická pánská pedikúra.', price: 450, priceText: '450 Kč', duration: 60, tags: ['pánská'] },
  { id: 'pedi-gel-lak', category: 'pedicure', name: 'Pedikúra & Gel lak', desc: 'Pedikúra s aplikací gel laku.', price: 500, priceText: '500 Kč', duration: 75, tags: ['gel lak'] },
  { id: 'pedi-polish', category: 'pedicure', name: 'Lakování nehtů na nohou', desc: 'Lakování nehtů na nohou.', price: 350, priceText: '350 Kč', duration: 35, tags: ['lakování'] },
  { id: 'pedi-feet-massage', category: 'pedicure', name: 'Masáž nohou 20 min', desc: 'Krátká relaxační masáž nohou.', price: 290, priceText: '290 Kč', duration: 20, tags: ['masáž nohou'] },

  { id: 'art-handpaint', category: 'nailart', name: 'Ruční malování podle složitosti', desc: 'Individuální ruční nail art podle náročnosti.', price: 10, priceText: '10-250 Kč', duration: 15, tags: ['nail art'] },
  { id: 'art-one-nail', category: 'nailart', name: 'Třpytky nebo jiná barva na 1 nehet', desc: 'Zdobení jednoho nehtu.', price: 10, priceText: '10 Kč', duration: 5, tags: ['třpytky'] },
  { id: 'art-glitter-all', category: 'nailart', name: 'Třpytky na všechny nehty', desc: 'Třpytivý efekt na všechny nehty.', price: 50, priceText: '50 Kč', duration: 10, tags: ['třpytky'] },
  { id: 'art-chrome-all', category: 'nailart', name: 'Chrome na všechny nehty', desc: 'Chrome efekt na všechny nehty.', price: 100, priceText: '100 Kč', duration: 15, tags: ['chrome'] },
  { id: 'art-length', category: 'nailart', name: 'Délka nehtů', desc: 'Příplatek podle délky nehtů.', price: 30, priceText: '30-150 Kč', duration: 10, tags: ['délka'] },
  { id: 'art-cat-eye', category: 'nailart', name: 'Cat Eye na všechny nehty', desc: 'Magnetický Cat Eye efekt.', price: 50, priceText: '50 Kč', duration: 10, tags: ['cat eye'] },

  { id: 'gel-new-color', category: 'modelage', name: 'Nové gelové nehty s lakováním', desc: 'Nová gelová modeláž s barevným lakováním.', price: 520, priceText: '520 Kč', duration: 90, tags: ['gelové'] },
  { id: 'gel-new-french', category: 'modelage', name: 'Nové gelové nehty s francií', desc: 'Nová gelová modeláž s francouzskou manikúrou.', price: 550, priceText: '550 Kč', duration: 100, tags: ['gelové', 'francie'] },
  { id: 'gel-new-ombre', category: 'modelage', name: 'Nové gelové nehty s ombré', desc: 'Nová gelová modeláž s ombré efektem.', price: 550, priceText: '550 Kč', duration: 100, tags: ['gelové', 'ombré'] },
  { id: 'acryl-new-color', category: 'modelage', name: 'Nové akrylové nehty s lakováním', desc: 'Nová akrylová modeláž s barevným lakováním.', price: 500, priceText: '500 Kč', duration: 90, tags: ['akrylové'] },
  { id: 'acryl-new-french', category: 'modelage', name: 'Nové akrylové nehty s francií', desc: 'Nová akrylová modeláž s francouzskou manikúrou.', price: 520, priceText: '520 Kč', duration: 100, tags: ['akrylové', 'francie'] },
  { id: 'acryl-new-ombre', category: 'modelage', name: 'Nové akrylové nehty s ombré', desc: 'Nová akrylová modeláž s ombré efektem.', price: 520, priceText: '520 Kč', duration: 100, tags: ['akrylové', 'ombré'] },
  { id: 'gel-fill-color', category: 'modelage', name: 'Doplnění gelových nehtů s lakováním', desc: 'Doplnění gelové modeláže s lakováním.', price: 490, priceText: '490 Kč', duration: 80, tags: ['doplnění', 'gelové'] },
  { id: 'gel-fill-french', category: 'modelage', name: 'Doplnění gelových nehtů s francií', desc: 'Doplnění gelové modeláže s francií.', price: 520, priceText: '520 Kč', duration: 90, tags: ['doplnění', 'francie'] },
  { id: 'gel-fill-ombre', category: 'modelage', name: 'Doplnění gelových nehtů s ombré', desc: 'Doplnění gelové modeláže s ombré.', price: 520, priceText: '520 Kč', duration: 90, tags: ['doplnění', 'ombré'] },
  { id: 'acryl-fill-color', category: 'modelage', name: 'Doplnění akrylových nehtů s lakováním', desc: 'Doplnění akrylové modeláže s lakováním.', price: 480, priceText: '480 Kč', duration: 80, tags: ['doplnění', 'akrylové'] },
  { id: 'acryl-fill-french', category: 'modelage', name: 'Doplnění akrylových nehtů s francií', desc: 'Doplnění akrylové modeláže s francií.', price: 500, priceText: '500 Kč', duration: 90, tags: ['doplnění', 'francie'] },
  { id: 'acryl-fill-ombre', category: 'modelage', name: 'Doplnění akrylových nehtů s ombré', desc: 'Doplnění akrylové modeláže s ombré.', price: 500, priceText: '500 Kč', duration: 90, tags: ['doplnění', 'ombré'] },

  { id: 'brow-color', category: 'browslashes', name: 'Barvení obočí', desc: 'Barvení obočí pro zvýraznění výrazu.', price: 100, priceText: '100 Kč', duration: 15, tags: ['obočí'] },
  { id: 'lash-color', category: 'browslashes', name: 'Barvení řas', desc: 'Barvení řas.', price: 100, priceText: '100 Kč', duration: 15, tags: ['řasy'] },
  { id: 'brow-shape', category: 'browslashes', name: 'Úprava obočí', desc: 'Tvarování a úprava obočí.', price: 50, priceText: '50 Kč', duration: 15, tags: ['obočí'] },
  { id: 'brow-shape-color', category: 'browslashes', name: 'Úprava & barvení obočí', desc: 'Kompletní úprava a barvení obočí.', price: 150, priceText: '150 Kč', duration: 25, tags: ['obočí'] },
  { id: 'brow-lash-color', category: 'browslashes', name: 'Úprava & barvení obočí a řas', desc: 'Kombinovaná péče o obočí a řasy.', price: 250, priceText: '250 Kč', duration: 35, tags: ['obočí', 'řasy'] },
  { id: 'lash-lifting', category: 'browslashes', name: 'Lash lifting + barvení řas', desc: 'Lash lifting s barvením řas.', price: 500, priceText: '500 Kč', duration: 60, tags: ['lash lifting'] },
  { id: 'brow-lifting', category: 'browslashes', name: 'Brow lifting / laminace obočí', desc: 'Laminace obočí pro upravený a plnější vzhled.', price: 500, priceText: '500 Kč', duration: 60, tags: ['brow lifting'] },
  { id: 'lash-brow-lifting', category: 'browslashes', name: 'Lash lifting + Brow lifting', desc: 'Kombinace liftingu řas a obočí.', price: 850, priceText: '850 Kč', duration: 90, tags: ['lifting'] },
  { id: 'lash-11-new', category: 'browslashes', name: 'Prodlužování řas řasa na řasu - nový set', desc: 'Nový set metodou řasa na řasu.', price: 750, priceText: '750 Kč', duration: 100, tags: ['prodlužování řas'] },
  { id: 'lash-11-fill', category: 'browslashes', name: 'Prodlužování řas řasa na řasu - doplnění', desc: 'Doplnění metody řasa na řasu.', price: 550, priceText: '550 Kč', duration: 70, tags: ['doplnění řas'] },
  { id: 'lash-volume-new', category: 'browslashes', name: 'Volume řasy 3D-5D - nový set', desc: 'Nový set objemových řas.', price: 900, priceText: '900 Kč', duration: 120, tags: ['volume'] },
  { id: 'lash-volume-fill', category: 'browslashes', name: 'Volume řasy 3D-5D - doplnění', desc: 'Doplnění objemových řas.', price: 650, priceText: '650 Kč', duration: 80, tags: ['volume', 'doplnění'] },
  { id: 'lash-mega-new', category: 'browslashes', name: 'Mega Volume 6D-7D - nový set', desc: 'Nový set Mega Volume řas.', price: 1000, priceText: '1 000 Kč', duration: 130, tags: ['mega volume'] },
  { id: 'lash-mega-fill', category: 'browslashes', name: 'Mega Volume 6D-7D - doplnění', desc: 'Doplnění Mega Volume řas.', price: 700, priceText: '700 Kč', duration: 90, tags: ['mega volume', 'doplnění'] },
  { id: 'lash-remove', category: 'browslashes', name: 'Sundání řas', desc: 'Šetrné odstranění prodloužených řas.', price: 200, priceText: '200 Kč', duration: 30, tags: ['sundání'] },

  { id: 'voucher-custom', category: 'voucher', name: 'Dárkový poukaz na vybranou hodnotu', desc: 'Poukaz na libovolnou částku nebo konkrétní proceduru.', price: 0, priceText: 'dle hodnoty', duration: 10, tags: ['poukaz', 'dárek'] }
];
